### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by wuzehao16** [darrint/device-blocker-ui#1]
e:\test\rust\device-blocker-ui (master) (device-blocker-ui@1.0.0)
λ webpack --optimize-minimize --define process.env.NODE_ENV="'production'"
Hash: 09c66f9d0f0f18b5c59c
Version: webpack 1.15.0
Time: 17896ms
    Asset     Size  Chunks             Chunk Names
bundle.js  85.6 kB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built] [1 error]
    + 297 hidden modules

ERROR in ./src/index.js
Module build failed: SyntaxError: e:/test/rust/device-blocker-ui/src/index.js: Unexpected token (39:2)
```
  37 |
  38 | ReactDOM.render(
> 39 |   <Provider store={store}>
     |   ^
  40 |     <App />
  41 |   </Provider>,
  42 |   document.getElementById('content')
```
 @ multi main

**Comment by darrint** [comment]
Sorry I missed this earlier. I will take a look soon. I'm mystified at how you could run yarn and end up with a broken toolchain.

**Comment by darrint** [comment]
I left out the babel config file. Your issue should be fixed now.
